baseURL: "https://alenabraham.me/"
languageCode: en-us
title: Alen Abraham
theme: PaperMod
enableGitInfo: true

# Pagination settings
pagination:
  pagerSize: 200000

taxonomies:
  category: categories
  series: series
  tag: tags

params:
  #env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Alen Abraham"
  description: "Alen Abraham's personal website"
  keywords: [Alen, Abraham, Blog, Portfolio, Resume]
  # author: "Alen Abraham"
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light, auto
  disableThemeToggle: false

  # Analytics configuration
  analytics:
    plausible:
      enable: true
      domain: "alenabraham.me"
      
  mainSections: ["posts"]
  dailySections: ["daily"]

  # Search Configuration
  fuseOpts:
    isCaseSensitive: false
    includeScore: true
    includeMatches: true
    shouldSort: true
    minMatchCharLength: 2
    keys: ["title", "permalink", "summary", "content", "categories", "section"]
    location: 0
    threshold: 0.4
    distance: 100
    ignoreLocation: true
    findAllMatches: true
    limit: 10

  # home infos
  homeInfoParams:
    Title: "Scale, Stabilize and Secure Systems"
    Content:
    #   Intro: I'm Alen, and welcome to my random thoughts.
    #   About: about
    #   Action: If you

  socialIcons:
    - name: Github
      url: "https://github.com/abrahamalen/"
    - name: Twitter
      url: "https://twitter.com/op__trojan/"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/alenabraham/"
    - name: "Behance"
      url: "https://www.behance.net/alenabraham"
    - name: Medium
      url: "https://medium.com/@alen-abraham"
    # - name: Buy me a coffee
    #   url: "https://www.buymeacoffee.com/alenabraham"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

    ShowReadingTime: true
    ShowLastMod: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowWordCount: false
    ShowRssButtonInSectionTermList: false
    UseHugoToc: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    images: ["images/preview.png", "Alen Abraham", "https://alenabraham.me/"]

menu:
  main:
    - name: Archives
      url: /archives/
      weight: 5
    - name: Categories
      url: /categories/
      weight: 10
    - name: About
      url: /about/
      weight: 20

outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS
  term:
    - HTML
    - RSS
